[project]
name = "part2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shubham Kumar", email = "shubamkumar3039@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
part2 = "part2:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
