[project]
name = "part3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shubham Kumar", email = "shubamkumar3039@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "numpy>=2.4.6",
    "python-dotenv>=1.2.4",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
part3 = "part3:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
